//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Configration.Consume.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="model", Namespace="http://schemas.datacontract.org/2004/07/Configration.Domain.Entities")]
    [System.SerializableAttribute()]
    public partial class model : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IConfigrationService")]
    public interface IConfigrationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigrationService/GetAllStudents", ReplyAction="http://tempuri.org/IConfigrationService/GetAllStudentsResponse")]
        Configration.Consume.ServiceReference1.model[] GetAllStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigrationService/GetAllStudents", ReplyAction="http://tempuri.org/IConfigrationService/GetAllStudentsResponse")]
        System.Threading.Tasks.Task<Configration.Consume.ServiceReference1.model[]> GetAllStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigrationService/GetAllInstructors", ReplyAction="http://tempuri.org/IConfigrationService/GetAllInstructorsResponse")]
        Configration.Consume.ServiceReference1.model[] GetAllInstructors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigrationService/GetAllInstructors", ReplyAction="http://tempuri.org/IConfigrationService/GetAllInstructorsResponse")]
        System.Threading.Tasks.Task<Configration.Consume.ServiceReference1.model[]> GetAllInstructorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigrationService/GetAllITIBranches", ReplyAction="http://tempuri.org/IConfigrationService/GetAllITIBranchesResponse")]
        Configration.Consume.ServiceReference1.model[] GetAllITIBranches();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigrationService/GetAllITIBranches", ReplyAction="http://tempuri.org/IConfigrationService/GetAllITIBranchesResponse")]
        System.Threading.Tasks.Task<Configration.Consume.ServiceReference1.model[]> GetAllITIBranchesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigrationService/GetAllBranchesConfigKeys", ReplyAction="http://tempuri.org/IConfigrationService/GetAllBranchesConfigKeysResponse")]
        Configration.Consume.ServiceReference1.model[] GetAllBranchesConfigKeys();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigrationService/GetAllBranchesConfigKeys", ReplyAction="http://tempuri.org/IConfigrationService/GetAllBranchesConfigKeysResponse")]
        System.Threading.Tasks.Task<Configration.Consume.ServiceReference1.model[]> GetAllBranchesConfigKeysAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigrationService/GetAllStudentsConfigKeys", ReplyAction="http://tempuri.org/IConfigrationService/GetAllStudentsConfigKeysResponse")]
        Configration.Consume.ServiceReference1.model[] GetAllStudentsConfigKeys();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigrationService/GetAllStudentsConfigKeys", ReplyAction="http://tempuri.org/IConfigrationService/GetAllStudentsConfigKeysResponse")]
        System.Threading.Tasks.Task<Configration.Consume.ServiceReference1.model[]> GetAllStudentsConfigKeysAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigrationService/GetAllInstructorsConfigKeys", ReplyAction="http://tempuri.org/IConfigrationService/GetAllInstructorsConfigKeysResponse")]
        Configration.Consume.ServiceReference1.model[] GetAllInstructorsConfigKeys();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigrationService/GetAllInstructorsConfigKeys", ReplyAction="http://tempuri.org/IConfigrationService/GetAllInstructorsConfigKeysResponse")]
        System.Threading.Tasks.Task<Configration.Consume.ServiceReference1.model[]> GetAllInstructorsConfigKeysAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigrationService/GetITIBranchConfigValue", ReplyAction="http://tempuri.org/IConfigrationService/GetITIBranchConfigValueResponse")]
        string GetITIBranchConfigValue(int BranchID, int BranchConfigKeyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigrationService/GetITIBranchConfigValue", ReplyAction="http://tempuri.org/IConfigrationService/GetITIBranchConfigValueResponse")]
        System.Threading.Tasks.Task<string> GetITIBranchConfigValueAsync(int BranchID, int BranchConfigKeyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigrationService/GetInstructorConfigValue", ReplyAction="http://tempuri.org/IConfigrationService/GetInstructorConfigValueResponse")]
        string GetInstructorConfigValue(int InstructorID, int InstructorConfigKeyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigrationService/GetInstructorConfigValue", ReplyAction="http://tempuri.org/IConfigrationService/GetInstructorConfigValueResponse")]
        System.Threading.Tasks.Task<string> GetInstructorConfigValueAsync(int InstructorID, int InstructorConfigKeyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigrationService/GetStudentConfigValue", ReplyAction="http://tempuri.org/IConfigrationService/GetStudentConfigValueResponse")]
        string GetStudentConfigValue(int StudentID, int StudentConfigKEyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigrationService/GetStudentConfigValue", ReplyAction="http://tempuri.org/IConfigrationService/GetStudentConfigValueResponse")]
        System.Threading.Tasks.Task<string> GetStudentConfigValueAsync(int StudentID, int StudentConfigKEyId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConfigrationServiceChannel : Configration.Consume.ServiceReference1.IConfigrationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConfigrationServiceClient : System.ServiceModel.ClientBase<Configration.Consume.ServiceReference1.IConfigrationService>, Configration.Consume.ServiceReference1.IConfigrationService {
        
        public ConfigrationServiceClient() {
        }
        
        public ConfigrationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConfigrationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigrationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Configration.Consume.ServiceReference1.model[] GetAllStudents() {
            return base.Channel.GetAllStudents();
        }
        
        public System.Threading.Tasks.Task<Configration.Consume.ServiceReference1.model[]> GetAllStudentsAsync() {
            return base.Channel.GetAllStudentsAsync();
        }
        
        public Configration.Consume.ServiceReference1.model[] GetAllInstructors() {
            return base.Channel.GetAllInstructors();
        }
        
        public System.Threading.Tasks.Task<Configration.Consume.ServiceReference1.model[]> GetAllInstructorsAsync() {
            return base.Channel.GetAllInstructorsAsync();
        }
        
        public Configration.Consume.ServiceReference1.model[] GetAllITIBranches() {
            return base.Channel.GetAllITIBranches();
        }
        
        public System.Threading.Tasks.Task<Configration.Consume.ServiceReference1.model[]> GetAllITIBranchesAsync() {
            return base.Channel.GetAllITIBranchesAsync();
        }
        
        public Configration.Consume.ServiceReference1.model[] GetAllBranchesConfigKeys() {
            return base.Channel.GetAllBranchesConfigKeys();
        }
        
        public System.Threading.Tasks.Task<Configration.Consume.ServiceReference1.model[]> GetAllBranchesConfigKeysAsync() {
            return base.Channel.GetAllBranchesConfigKeysAsync();
        }
        
        public Configration.Consume.ServiceReference1.model[] GetAllStudentsConfigKeys() {
            return base.Channel.GetAllStudentsConfigKeys();
        }
        
        public System.Threading.Tasks.Task<Configration.Consume.ServiceReference1.model[]> GetAllStudentsConfigKeysAsync() {
            return base.Channel.GetAllStudentsConfigKeysAsync();
        }
        
        public Configration.Consume.ServiceReference1.model[] GetAllInstructorsConfigKeys() {
            return base.Channel.GetAllInstructorsConfigKeys();
        }
        
        public System.Threading.Tasks.Task<Configration.Consume.ServiceReference1.model[]> GetAllInstructorsConfigKeysAsync() {
            return base.Channel.GetAllInstructorsConfigKeysAsync();
        }
        
        public string GetITIBranchConfigValue(int BranchID, int BranchConfigKeyId) {
            return base.Channel.GetITIBranchConfigValue(BranchID, BranchConfigKeyId);
        }
        
        public System.Threading.Tasks.Task<string> GetITIBranchConfigValueAsync(int BranchID, int BranchConfigKeyId) {
            return base.Channel.GetITIBranchConfigValueAsync(BranchID, BranchConfigKeyId);
        }
        
        public string GetInstructorConfigValue(int InstructorID, int InstructorConfigKeyId) {
            return base.Channel.GetInstructorConfigValue(InstructorID, InstructorConfigKeyId);
        }
        
        public System.Threading.Tasks.Task<string> GetInstructorConfigValueAsync(int InstructorID, int InstructorConfigKeyId) {
            return base.Channel.GetInstructorConfigValueAsync(InstructorID, InstructorConfigKeyId);
        }
        
        public string GetStudentConfigValue(int StudentID, int StudentConfigKEyId) {
            return base.Channel.GetStudentConfigValue(StudentID, StudentConfigKEyId);
        }
        
        public System.Threading.Tasks.Task<string> GetStudentConfigValueAsync(int StudentID, int StudentConfigKEyId) {
            return base.Channel.GetStudentConfigValueAsync(StudentID, StudentConfigKEyId);
        }
    }
}
